-- Development Phase 02, Sprint 2 — the reservation engine.
--
-- Generated by drizzle-kit, then edited by hand:
--   * the backfill runs before the new CHECK constraints that depend on it;
--   * foreign keys the TypeScript schema cannot declare (the cashiering schema imports the
--     bookings schema) are appended at the end;
--   * the new booking_action values are the LAST statements. Drizzle applies every pending
--     migration in one transaction, and a value added there cannot be used until it commits, so
--     nothing in any migration may use them.
CREATE TABLE IF NOT EXISTS "reservation_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"idempotency_key" text NOT NULL,
	"request_hash" text NOT NULL,
	"user_id" uuid,
	"response" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "reservation_requests_tenant_key_uq" UNIQUE("tenant_id","idempotency_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ledger_account_rates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"ledger_account_id" uuid NOT NULL,
	"property_id" uuid NOT NULL,
	"room_id" uuid NOT NULL,
	"rate_plan_id" uuid,
	"valid_from" date NOT NULL,
	"valid_to" date NOT NULL,
	"mode" text DEFAULT 'fixed' NOT NULL,
	"value" numeric(12, 2) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_account_rates_range_valid" CHECK ("ledger_account_rates"."valid_to" >= "ledger_account_rates"."valid_from"),
	CONSTRAINT "ledger_account_rates_mode_valid" CHECK ("ledger_account_rates"."mode" in ('fixed', 'discount_pct')),
	CONSTRAINT "ledger_account_rates_value_valid" CHECK ("ledger_account_rates"."value" >= 0 and ("ledger_account_rates"."mode" <> 'discount_pct' or "ledger_account_rates"."value" <= 100))
);
--> statement-breakpoint
ALTER TABLE "rate_plans" ADD COLUMN "audience" text DEFAULT 'all' NOT NULL;--> statement-breakpoint
ALTER TABLE "rate_plans" ADD COLUMN "market_segment_id" uuid;--> statement-breakpoint
ALTER TABLE "tax_types" ADD COLUMN "exemptible" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_days" ADD COLUMN "list_selling_price" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "booking_days" ADD COLUMN "rate_source" text DEFAULT 'calendar' NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_days" ADD COLUMN "tax_lines" jsonb;--> statement-breakpoint
ALTER TABLE "booking_groups" ADD COLUMN "kind" text DEFAULT 'manual' NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_groups" ADD COLUMN "owner_customer_id" uuid;--> statement-breakpoint
ALTER TABLE "booking_groups" ADD COLUMN "bill_to" text;--> statement-breakpoint
ALTER TABLE "booking_groups" ADD COLUMN "business_source_id" uuid;--> statement-breakpoint
ALTER TABLE "booking_rooms" ADD COLUMN "child_ages" integer[] DEFAULT '{}'::integer[] NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_rooms" ADD COLUMN "extra_beds" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_rooms" ADD COLUMN "preferred_room_unit_id" uuid;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "reservation_kind" text DEFAULT 'hold_unconfirm' NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "inventory_held" boolean GENERATED ALWAYS AS (status not in ('Cancelled', 'Rejected') and reservation_kind not in ('inquiry', 'online_failed')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "inventory_released_from" date;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "hold_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "hold_reminded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "origin" text DEFAULT 'direct' NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "residency" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "arrival_time" time;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "departure_time" time;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "market_segment_id" uuid;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "sales_person_id" uuid;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "voucher_no" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "created_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "sibling_index" integer;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "pricing" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "options" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "levy_exempt" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "levy_collected_by_channel" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "title" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "given_name" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "family_name" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "mobile_e164" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "whatsapp" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "nationality_code" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "country_code" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "state" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "zip" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "gender" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "occupation" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "tax_id" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "company_name" text;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "consent_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "consent_version" text;--> statement-breakpoint
-- Backfill (hand-written). ---------------------------------------------------------------
--
-- Every existing booking gets a reservation kind that matches what it already does:
-- a Pending booking holds its rooms today and has no release time, so it stays the column's
-- default — an unconfirmed hold that is never released automatically; everything else is a
-- confirmed booking. inventory_held is generated from status and kind, so Cancelled and Rejected
-- bookings come out as not holding without being touched.
UPDATE "bookings" SET "reservation_kind" = 'confirm' WHERE "status" <> 'Pending';
--> statement-breakpoint
UPDATE "bookings" SET "origin" = 'ota' WHERE "source" = 'OTA';
--> statement-breakpoint
-- Every existing night was priced from the rate calendar, so its list price is what was charged.
UPDATE "booking_days" SET "list_selling_price" = "selling_price" WHERE "list_selling_price" IS NULL;
--> statement-breakpoint
-- A service charge belongs to the hotel, not the state: a tax-exempt guest still pays it.
UPDATE "tax_types" SET "exemptible" = false WHERE "name" ~* 'service';
--> statement-breakpoint
-- The group foreign key below would refuse a booking pointing at a group that no longer exists.
UPDATE "bookings" b SET "group_id" = NULL
WHERE b."group_id" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "booking_groups" g WHERE g."id" = b."group_id");
--> statement-breakpoint
-- booking_days gains UNIQUE(booking_id, date) below. Bookings only ever write one row per night
-- (amend deletes and re-inserts), so a duplicate here means corrupt data: the migration stops
-- rather than guess which row is right.
DO $$
DECLARE dupes integer;
BEGIN
  SELECT count(*) INTO dupes FROM (
    SELECT 1 FROM "booking_days" GROUP BY "booking_id", "date" HAVING count(*) > 1
  ) d;
  IF dupes > 0 THEN
    RAISE EXCEPTION 'booking_days has % duplicated booking nights; resolve them before migrating', dupes;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "reservation_requests" ADD CONSTRAINT "reservation_requests_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "reservation_requests" ADD CONSTRAINT "reservation_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_account_rates" ADD CONSTRAINT "ledger_account_rates_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_account_rates" ADD CONSTRAINT "ledger_account_rates_ledger_account_id_ledger_accounts_id_fk" FOREIGN KEY ("ledger_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_account_rates" ADD CONSTRAINT "ledger_account_rates_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_account_rates" ADD CONSTRAINT "ledger_account_rates_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_account_rates" ADD CONSTRAINT "ledger_account_rates_rate_plan_id_rate_plans_id_fk" FOREIGN KEY ("rate_plan_id") REFERENCES "public"."rate_plans"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reservation_requests_tenant_created_idx" ON "reservation_requests" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ledger_account_rates_lookup_idx" ON "ledger_account_rates" USING btree ("ledger_account_id","room_id","valid_from");--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rate_plans" ADD CONSTRAINT "rate_plans_market_segment_id_market_segments_id_fk" FOREIGN KEY ("market_segment_id") REFERENCES "public"."market_segments"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "booking_groups" ADD CONSTRAINT "booking_groups_owner_customer_id_customers_id_fk" FOREIGN KEY ("owner_customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "booking_rooms" ADD CONSTRAINT "booking_rooms_preferred_room_unit_id_room_units_id_fk" FOREIGN KEY ("preferred_room_unit_id") REFERENCES "public"."room_units"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_group_id_booking_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."booking_groups"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_market_segment_id_market_segments_id_fk" FOREIGN KEY ("market_segment_id") REFERENCES "public"."market_segments"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_property_checkin_idx" ON "bookings" USING btree ("property_id","checkin");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_property_created_idx" ON "bookings" USING btree ("property_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_group_idx" ON "bookings" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_customer_idx" ON "bookings" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_hold_until_idx" ON "bookings" USING btree ("hold_until") WHERE "bookings"."hold_until" is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_tenant_email_idx" ON "customers" USING btree ("tenant_id",lower("email"));--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_tenant_mobile_idx" ON "customers" USING btree ("tenant_id","mobile_e164");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_booking_idx" ON "payments" USING btree ("booking_id");--> statement-breakpoint
ALTER TABLE "booking_days" ADD CONSTRAINT "booking_days_booking_date_uq" UNIQUE("booking_id","date");--> statement-breakpoint
ALTER TABLE "rate_plans" ADD CONSTRAINT "rate_plans_audience_valid" CHECK ("rate_plans"."audience" in ('all', 'local', 'foreign'));--> statement-breakpoint
ALTER TABLE "booking_days" ADD CONSTRAINT "booking_days_rate_source_valid" CHECK ("booking_days"."rate_source" in ('calendar', 'override', 'contract', 'complimentary'));--> statement-breakpoint
ALTER TABLE "booking_groups" ADD CONSTRAINT "booking_groups_kind_valid" CHECK ("booking_groups"."kind" in ('manual', 'reservation'));--> statement-breakpoint
ALTER TABLE "booking_groups" ADD CONSTRAINT "booking_groups_bill_to_valid" CHECK ("booking_groups"."bill_to" is null or "booking_groups"."bill_to" in ('guest', 'company', 'group_owner', 'company_room_tax'));--> statement-breakpoint
ALTER TABLE "booking_rooms" ADD CONSTRAINT "booking_rooms_pax_valid" CHECK ("booking_rooms"."adults" >= 0 and "booking_rooms"."children" >= 0 and "booking_rooms"."extra_beds" >= 0);--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_reservation_kind_valid" CHECK ("bookings"."reservation_kind" in ('confirm', 'inquiry', 'online_failed', 'hold_confirm', 'hold_unconfirm'));--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_kind_matches_status" CHECK (("bookings"."status" <> 'Pending' or "bookings"."reservation_kind" in ('inquiry', 'online_failed', 'hold_unconfirm')) and ("bookings"."status" not in ('Approved', 'CheckedIn', 'CheckedOut', 'NoShow') or "bookings"."reservation_kind" in ('confirm', 'hold_confirm')));--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_hold_until_needs_hold_kind" CHECK ("bookings"."hold_until" is null or "bookings"."reservation_kind" in ('hold_confirm', 'hold_unconfirm'));--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_origin_valid" CHECK ("bookings"."origin" in ('direct', 'ota', 'travel_agent', 'corporate'));--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_residency_valid" CHECK ("bookings"."residency" is null or "bookings"."residency" in ('local', 'foreign'));--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_inventory_released_from_in_stay" CHECK ("bookings"."inventory_released_from" is null or ("bookings"."inventory_released_from" > "bookings"."checkin" and "bookings"."inventory_released_from" <= "bookings"."checkout"));--> statement-breakpoint
ALTER TABLE "customers" ADD CONSTRAINT "customers_gender_valid" CHECK ("customers"."gender" is null or "customers"."gender" in ('male', 'female', 'other'));--> statement-breakpoint

-- Hand-written foreign keys (see the note at the top). -------------------------------------
-- These columns were never written before this sprint, but clear anything dangling first.
UPDATE "bookings" b SET "business_source_id" = NULL
WHERE b."business_source_id" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "business_sources" s WHERE s."id" = b."business_source_id");
--> statement-breakpoint
UPDATE "bookings" b SET "ledger_account_id" = NULL
WHERE b."ledger_account_id" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "ledger_accounts" a WHERE a."id" = b."ledger_account_id");
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_business_source_id_business_sources_id_fk" FOREIGN KEY ("business_source_id") REFERENCES "public"."business_sources"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_ledger_account_id_ledger_accounts_id_fk" FOREIGN KEY ("ledger_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bookings" ADD CONSTRAINT "bookings_sales_person_id_ledger_accounts_id_fk" FOREIGN KEY ("sales_person_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "booking_groups" ADD CONSTRAINT "booking_groups_business_source_id_business_sources_id_fk" FOREIGN KEY ("business_source_id") REFERENCES "public"."business_sources"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_business_source_idx" ON "bookings" ("business_source_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bookings_ledger_account_idx" ON "bookings" ("ledger_account_id");
--> statement-breakpoint

-- New enum values: last, and unused by any migration SQL. ---------------------------------
ALTER TYPE "public"."booking_action" ADD VALUE IF NOT EXISTS 'held';--> statement-breakpoint
ALTER TYPE "public"."booking_action" ADD VALUE IF NOT EXISTS 'released';--> statement-breakpoint
ALTER TYPE "public"."booking_action" ADD VALUE IF NOT EXISTS 'confirmed';
